# Generated by Django 4.1.3 on 2022-11-19 20:54

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_article_author_articleseries_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='default/no_miage.jpg', max_length=255, upload_to=main.models.Article.image_upload_to),
        ),
        migrations.AddField(
            model_name='articleseries',
            name='image',
            field=models.ImageField(default='default/no_miage.jpg', max_length=255, upload_to=main.models.ArticleSeries.image_upload_to),
        ),
    ]
