# Generated by Django 4.1.3 on 2022-11-19 20:56

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_article_image_articleseries_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='default/no_image.jpg', max_length=255, upload_to=main.models.Article.image_upload_to),
        ),
        migrations.AlterField(
            model_name='articleseries',
            name='image',
            field=models.ImageField(default='default/no_image.jpg', max_length=255, upload_to=main.models.ArticleSeries.image_upload_to),
        ),
    ]
